In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Orignal_Data.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3768780 entries, 0 to 3768779
Data columns (total 15 columns):
 #   Column                      Dtype  
---  ------                      -----  
 0   container_id                object 
 1   shipment_id                 object 
 2   production_year             float64
 3   equipment_size              int64  
 4   equipment_sound_status      bool   
 5   cargo_weight_kg             int64  
 6   parent_commodity_name       object 
 7   damage_code                 float64
 8   work_order_id               float64
 9   shop_id                     object 
 10  completion_date             object 
 11  repair_codes                object 
 12  move_timestamp              object 
 13  load_port_location_id       object 
 14  discharge_port_location_id  object 
dtypes: bool(1), float64(3), int64(2), object(9)
memory usage: 406.1+ MB


In [4]:
data.head()

container_id    shipment_id  production_year  equipment_size  \
0  AMFU8749302  EO5MF5U6418KB           2004.0              40   
1  AMFU8766439            NaN           2005.0              40   
2  AMFU8902068            NaN           2007.0              40   
3   APMU100136            NaN           2002.0              20   
4   APMU100460            NaN           2006.0              20   

   equipment_sound_status  cargo_weight_kg parent_commodity_name  damage_code  \
0                    True            24100  Textiles and apparel          NaN   
1                    True                0    Plastic and rubber          NaN   
2                    True                0                 Paper          NaN   
3                    True                0                   NaN          NaN   
4                    True                0                   NaN          NaN   

   work_order_id shop_id           completion_date  \
0    114389387.0     Z74  2023-05-28T01:32:12.000Z   
1    115005053.0     9JJ  2023-06-19T05:49:41.000Z   
2    113459950.0     9TE  2023-05-08T07:27:03.000Z   
3     98434172.0     2TR  2021-08-17T09:11:31.000Z   
4            NaN     NaN                       NaN   

                         repair_codes            move_timestamp  \
0  5131;1114;1117;1115;5483;1112;0008  2023-06-07T09:43:00.000Z   
1                                0915  2023-05-27T06:36:00.000Z   
2                      0929;0915;5271  2023-03-17T16:22:00.000Z   
3                                0909                       NaN   
4                                 NaN                       NaN   

  load_port_location_id discharge_port_location_id  
0               CNSGHY3                    MYTPPTM  
1               MYTPPTM                    INJHTGT  
2               OMSLVTM                    INPPVTM  
3                   NaN                        NaN  
4                   NaN                        NaN

In [5]:
data['equipment_sound_status'].describe()

count     3768780
unique          2
top          True
freq      3579477
Name: equipment_sound_status, dtype: object

In [6]:
#Cleaning unwanted rows to equally split in 80:20 train test data
value_to_remove = True
num_rows_to_remove = 3100000

num_rows = len(data[data['equipment_sound_status'] == value_to_remove])
num_rows_to_remove = min(num_rows, num_rows_to_remove)

# Remove a limited number of rows with the specific value
data = data.drop(data[data['equipment_sound_status'] == value_to_remove].index[:num_rows_to_remove])

In [7]:
data['equipment_sound_status'].describe()

count     668780
unique         2
top         True
freq      479477
Name: equipment_sound_status, dtype: object

In [8]:
data.to_csv('cleaned_dpm_data.csv', index= False)

In [9]:
df = pd.read_csv('cleaned_dpm_data.csv')

In [10]:
df.head()

container_id shipment_id  production_year  equipment_size  \
0  APMU8060215         NaN           2003.0              40   
1  BMOU4155553         NaN           2008.0              40   
2  BMOU4163923         NaN           2008.0              40   
3  BOIU3933150         NaN           2013.0              20   
4  BSIU2028792         NaN           2004.0              20   

   equipment_sound_status  cargo_weight_kg  \
0                   False                0   
1                   False            25135   
2                   False                0   
3                   False                0   
4                   False                0   

                               parent_commodity_name  damage_code  \
0                                      Oils and fats          2.0   
1               Miscellaneous manufactured materials          2.0   
2                       Hides, fur, leather and skin          2.0   
3  Salt, sulphur, earths and stone, plastering ma...          2.0   
4                                 Plastic and rubber          2.0   

   work_order_id shop_id           completion_date  \
0    111076120.0     2EQ  2023-01-10T03:05:28.000Z   
1    111034167.0     U03  2023-02-16T10:24:01.000Z   
2    107658816.0     N90  2022-08-17T12:20:28.000Z   
3     96419279.0     V70  2021-05-29T08:56:24.000Z   
4    114006728.0     J58  2023-05-17T21:43:04.000Z   

                    repair_codes            move_timestamp  \
0       0005;1116;1115;0914;0928  2023-05-23T13:00:00.000Z   
1                      0003;5524  2023-05-30T02:00:00.000Z   
2  7892;0920;0003;0959;0928;7891  2023-04-10T18:30:00.000Z   
3       6171;0920;0927;0003;6701  2023-04-23T09:39:00.000Z   
4                 0003;0928;6521  2023-06-01T12:02:00.000Z   

  load_port_location_id discharge_port_location_id  
0               MYTPPTM                    KRINCHJ  
1               USJAXDP                    BRRIOTT  
2               CNNPOTN                    IDJKTT1  
3               NZAKLTM                    NZNELPT  
4               CNTSTQQ                    VNSGNCL

In [11]:
# Fill missing values in the 'RepairCode' column with an empty string
df['repair_codes'].fillna('', inplace=True)

# Create a new column to store the count of repair codes
df['Count_Of_Work_Order'] = df['repair_codes'].apply(lambda x: len(str(x).split(';')) if x else 0)

# Print the updated DataFrame
print(df['Count_Of_Work_Order'])

0         5
1         2
2         6
3         5
4         3
         ..
668775    1
668776    3
668777    0
668778    0
668779    0
Name: Count_Of_Work_Order, Length: 668780, dtype: int64


In [12]:
#Dropping unwanted attributes
df.drop(['container_id', 'repair_codes','damage_code'], inplace = True, axis=1)

In [13]:
df.columns

Index(['shipment_id', 'production_year', 'equipment_size',
       'equipment_sound_status', 'cargo_weight_kg', 'parent_commodity_name',
       'work_order_id', 'shop_id', 'completion_date', 'move_timestamp',
       'load_port_location_id', 'discharge_port_location_id',
       'Count_Of_Work_Order'],
      dtype='object')

In [14]:
from sklearn.preprocessing import LabelEncoder

# Assuming you have multiple categorical columns named 'category1', 'category2', 'category3' in your data
categorical_columns = [ 'parent_commodity_name', 'shop_id', 'load_port_location_id',
       'discharge_port_location_id']

# Create an instance of LabelEncoder for each categorical column
label_encoders = {}

for column in categorical_columns:
    label_encoders[column] = LabelEncoder()
    label_encoders[column].fit(df[column])

# Transform the categorical columns into encoded labels
for column in categorical_columns:
    df[column + '_encoded'] = label_encoders[column].transform(df[column])

In [15]:
df['equipment_sound_status'].describe()

count     668780
unique         2
top         True
freq      479477
Name: equipment_sound_status, dtype: object

In [16]:
df.to_csv('encoded.csv', index=False)

In [17]:
# Assigning predicted and explanatory variables
y = df['equipment_sound_status']
X = df.drop(['shipment_id', 'work_order_id','parent_commodity_name', 'shop_id', 'load_port_location_id',
       'discharge_port_location_id','equipment_sound_status', 'move_timestamp','completion_date'],axis=1)

In [18]:
X.isnull().sum()

production_year                       2098
equipment_size                           0
cargo_weight_kg                          0
Count_Of_Work_Order                      0
parent_commodity_name_encoded            0
shop_id_encoded                          0
load_port_location_id_encoded            0
discharge_port_location_id_encoded       0
dtype: int64

In [19]:
X['production_year'].fillna(int(X['production_year'].median()), inplace=True)
X['Count_Of_Work_Order'].fillna(0, inplace=True)

In [20]:
X.isnull().sum()

production_year                       0
equipment_size                        0
cargo_weight_kg                       0
Count_Of_Work_Order                   0
parent_commodity_name_encoded         0
shop_id_encoded                       0
load_port_location_id_encoded         0
discharge_port_location_id_encoded    0
dtype: int64

In [21]:
X.head(5).T

0        1       2       3       4
production_year                     2003.0   2008.0  2008.0  2013.0  2004.0
equipment_size                        40.0     40.0    40.0    20.0    20.0
cargo_weight_kg                        0.0  25135.0     0.0     0.0     0.0
Count_Of_Work_Order                    5.0      2.0     6.0     5.0     3.0
parent_commodity_name_encoded         22.0     20.0    15.0    33.0    28.0
shop_id_encoded                       78.0   1222.0  1161.0  1238.0  1147.0
load_port_location_id_encoded        495.0    661.0   160.0   530.0   186.0
discharge_port_location_id_encoded   424.0     57.0   336.0   512.0   682.0

In [22]:
X.columns

Index(['production_year', 'equipment_size', 'cargo_weight_kg',
       'Count_Of_Work_Order', 'parent_commodity_name_encoded',
       'shop_id_encoded', 'load_port_location_id_encoded',
       'discharge_port_location_id_encoded'],
      dtype='object')

In [23]:
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Running the model
def classify(model, X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
    model.fit(X_train, y_train)
    cv_scores = cross_val_score(model, X_train, y_train, cv=5)
    
    
    print('===== CV on Training Data:')
    print('CV Array:', cv_scores)
    print('CV Mean:', cv_scores.mean())
    y_pred = model.predict(X_test)
    accuracy = metrics.accuracy_score(y_test, y_pred)
    print('===== Accuracy Score on Unseen Test Data:')
    print('Accuracy Score:', accuracy)
    f1 = f1_score(y_test, y_pred, average='weighted')
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    print(metrics.confusion_matrix(y_test, y_pred))
    print('=====F1:', f1)
    print('Precision is:',precision)
    print('Recall is:',recall)

In [24]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
classify(model, X, y)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

===== CV on Training Data:
CV Array: [0.7169665  0.71705061 0.71698519 0.71700388 0.71691712]
CV Mean: 0.7169846585059103
===== Accuracy Score on Unseen Test Data:
Accuracy Score: 0.7170444690331649
[[  306 37541]
 [  306 95603]]
=====F1: 0.603068103833976
Precision is: 0.6563458960261206
Recall is: 0.7170444690331649


C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [25]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
classify(model, X, y)

===== CV on Training Data:
CV Array: [0.58969207 0.5925424  0.59120602 0.59174805 0.59200591]
CV Mean: 0.5914388897825453
===== Accuracy Score on Unseen Test Data:
Accuracy Score: 0.5918239181793714
[[33733  4114]
 [50482 45427]]
=====F1: 0.6042901385127647
Precision is: 0.7708395551850308
Recall is: 0.5918239181793714


In [26]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
classify(model, X, y)

===== CV on Training Data:
CV Array: [0.76328209 0.76147844 0.76250642 0.76439419 0.76482188]
CV Mean: 0.7632966026295516
===== Accuracy Score on Unseen Test Data:
Accuracy Score: 0.7666422440862466
[[22779 15068]
 [16145 79764]]
=====F1: 0.7676202854956203
Precision is: 0.7687026732089756
Recall is: 0.7666422440862466


In [27]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
classify(model, X, y)


===== CV on Training Data:
CV Array: [0.80910238 0.80858838 0.81119574 0.8116817  0.81091361]
CV Mean: 0.8102963616907821
===== Accuracy Score on Unseen Test Data:
Accuracy Score: 0.81171685756153
[[21075 16772]
 [ 8412 87497]]
=====F1: 0.8039601234768422
Precision is: 0.8039400574781318
Recall is: 0.81171685756153


In [28]:
from xgboost import XGBClassifier

model = XGBClassifier()
classify(model, X, y)


===== CV on Training Data:
CV Array: [0.81864399 0.81938227 0.81742909 0.82075604 0.82190385]
CV Mean: 0.8196230492105118
===== Accuracy Score on Unseen Test Data:
Accuracy Score: 0.8204117946110828
[[20597 17250]
 [ 6771 89138]]
=====F1: 0.8106346700898054
Precision is: 0.8137319074690893
Recall is: 0.8204117946110828


## Testing Model with Dummy Data

In [29]:
#Testing the model
features = ['production_year', 'equipment_size', 'cargo_weight_kg',
       'Count_Of_Work_Order', 'parent_commodity_name_encoded', 'shop_id_encoded',
       'load_port_location_id_encoded', 'discharge_port_location_id_encoded']
values = [[2001,20,0,11,0,246,566,3]]

In [30]:
dataframe1 = pd.DataFrame(data = values, columns = features)

In [31]:
dataframe1.head().T

0
production_year                     2001
equipment_size                        20
cargo_weight_kg                        0
Count_Of_Work_Order                   11
parent_commodity_name_encoded          0
shop_id_encoded                      246
load_port_location_id_encoded        566
discharge_port_location_id_encoded     3

In [32]:
y_pred = model.predict(dataframe1)

In [33]:
print(y_pred)

[0]
